### ISSUE TITLE
[适配] Realme Q2 Pro

### ISSUE THREAD

**Issue by Yxiguan** [Sakion-Team/Re-Kernel#1]
### 你正在使用什么设备？

Realme RMX2117  MT6853

### 内核版本

4.14.186

### 内核开源地址

https://github.com/Yxiguan/android_kernel_mtk6853

**Comment by Nep-Timeline** [comment]
![image](https://github.com/Sakion-Team/Re-Kernel/assets/53483352/ff80a2d5-6ba5-4256-beae-56747dce6b63)
似乎无法构建？

**Comment by Nep-Timeline** [comment]
已对你的设备完成适配 下载请前往Devices查看
若内核出现问题 请在此issue中反馈
