### ISSUE TITLE
[适配] Realme GT Neo 闪速版

### ISSUE THREAD

**Issue by hzf1878** [Sakion-Team/Re-Kernel#2]
### 你正在使用什么设备？

realme RMX3350 MTK6893

### 内核版本

4.19.191+

### 内核开源地址

https://github.com/nishant6342/kernel_realme_RMX3031/tree/T-KernelSU

**Comment by hzf1878** [comment]
如果上面内核源码不可用就用下面这个，感谢开发者https://github.com/DogDayAndroid/Android-Builder

**Comment by Nep-Timeline** [comment]
内核源码地址不正确 为什么指向内核构建器？

**Comment by hzf1878** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by hzf1878** [comment]
> 内核源码地址不正确 为什么指向内核构建器？

抱歉没注意看链接，因为一直用那个编译内核的

**Comment by Nep-Timeline** [comment]
> > 内核源码地址不正确 为什么指向内核构建器？
> 
> 抱歉没注意看链接，因为一直用那个编译内核的

请重新修改内核源码链接

**Comment by hzf1878** [comment]
> ### 你正在使用什么设备？
> realme RMX3350 MTK6893
> 
> ### 内核版本
> 4.19.191+
> 
> ### 内核开源地址
> https://github.com/Sakion-Team/Re-Kernel



> ### 你正在使用什么设备？
> realme RMX3350 MTK6893
> 
> ### 内核版本
> 4.19.191+
> 
> ### 内核开源地址
> https://github.com/nishant6342/kernel_realme_RMX3031

**Comment by hzf1878** [comment]
> ### 你正在使用什么设备？
> realme RMX3350 MTK6893
> 
> ### 内核版本
> 4.19.191+
> 
> ### 内核开源地址
> https://github.com/nishant6342/kernel_realme_RMX3031

**Comment by hzf1878** [comment]
> > > 内核源码地址不正确 为什么指向内核构建器？
> > 
> > 
> > 抱歉没注意看链接，因为一直用那个编译内核的
> 
> 请重新修改内核源码链接

好的，已修改

**Comment by hzf1878** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
